//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysManagmentCarApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarageDBEntities : DbContext
    {
        public GarageDBEntities()
            : base("name=GarageDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Employess> Employess { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<FeaturesCars> FeaturesCars { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<NewEmployee> NewEmployee { get; set; }
        public virtual DbSet<ViewJob> ViewJob { get; set; }
    }
}
