//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysManagmentCarApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id { get; set; }
        public int idORDER { get; set; }
        public string idVin { get; set; }
        public int idEmployees { get; set; }
        public string idFeatures { get; set; }
        public Nullable<System.DateTime> DateHistory { get; set; }
        public string EventHistory { get; set; }
        public Nullable<bool> Result { get; set; }
        public string Descript { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Employess Employess { get; set; }
        public virtual FeaturesCars FeaturesCars { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
